### ISSUE TITLE
Convert lookaside upload cgi script to use fasjson instead of FAS api

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#12]
Current CentOS upload script (httpd) for lookaside content upload is based on x509 cert authentication (that will stay) but it's verifying "on the fly" group membership from FAS to ack/nack upload access to some folders in lookaside cache.

See https://github.com/CentOS/ansible-role-pagure/blob/master/files/upload.cgi#L85

This has to be converted to fasjson call (?) but let's write the requirements for that script to work

**Comment by abompard** [comment]
@StephenCoady has converted a lot of those FAS calls already, maybe he can check that one out?

**Comment by StephenCoady** [comment]
Yeah I think it would make sense to have a fasjson endpoint which just returns whether or not a user is a member of a group.

I'll try and get to writing acceptance criteria today for this.

**Comment by StephenCoady** [comment]
Acceptance Criteria:

* Fasjson has a new endpoint `/users/<username>/membership/<groupname>` or similar
* This endpoint should return either a 200 or a 404 depending on membership

DoD:
* Code coverage is 100%
* All tests passing
* Documentation is updated to reflect the changes

**Comment by abompard** [comment]
I've moved it to a ticket in the fasjson repo: fedora-infra/fasjson#123

**Comment by arrfab** [comment]
Moving it to "In progress" as this ticket was for the code running at the httpd level, that will query the endpoint you created, but I still need to write and test that code .. :)

**Comment by arrfab** [comment]
Following commit in pagure/lookaside role should  have all that is needed now, and tested successfully : https://github.com/CentOS/ansible-role-pagure/commit/5aae43a9c9dcac4ca9c308250af4bc84bdea1e63

Putting it as "blocked" for real test in Staging, when we'll have users/groups populated and also fasjson-client available as rpm and also able to sign CSR (currently broken)
