### ISSUE TITLE
Deploy a centos variant noggin instance in STG

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#19]
Per initial discussion, Fedora Infra would have to deploy a noggin instance using same setting as for Fedora but the visual theme (variable/parameter) , so like https://accounts.stg.centos.org pointing to same IPA STG instance but just using differnent hostname and different theme (see other card about PR review for this)

**Comment by arrfab** [comment]
We can now close this one as we decided to deploy like this, to avoid TLS renewal/deploy between centos/fedora different teams  : 

 * Fedora deployed noggin app in openshift, with the centos (merged now) theme as deploy option and ingress route
 * I deployed on the CentOS existing haproxy setup what's needed (through ansible) and so https://accounts.stg.centos.org is now running live and working

**Comment by szpak** [comment]
@arrfab I would like to test 2FA in the new Fedora/CentOS infrastructure. Unfortunately, there is `Registration is closed at the moment.`. How can I create an account there?

**Comment by arrfab** [comment]
@szpak : as the fas2ipa script was used to import/sync existing users from FAS/ACO, registration were closed in STG to ensure that people wouldn't register before the sync script was ran.
So if you had an existing user account in FAS and/or ACO, it was imported and only thing to do is to reset password

**Comment by szpak** [comment]
@arrfab Thanks, I haven't checked that before. I reset the password and was able to log in and to enable OTP. I even created a small [enhancement request](https://github.com/fedora-infra/noggin/issues/422) :-).
