### ISSUE TITLE
Modify fasjson DNS entry

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#22]
actually impacting STG but would also impact prod later : we shouldn't create CNAME for fasjson{.stg}.fedoraproject.org but instead real A (AAAA) record[s] in the DNS zone (see explanations below)

**Comment by arrfab** [comment]
Actually fasjson.stg.fedoraproject.org is just a CNAME: 
```
;; ANSWER SECTION:
fasjson.stg.fedoraproject.org. 300 IN	CNAME	wildcard.stg.fedoraproject.org.
wildcard.stg.fedoraproject.org.	300 IN	A	38.145.60.33
wildcard.stg.fedoraproject.org.	300 IN	A	38.145.60.32

```
On machines enrolled in IPA, installer modifies the default krb5.conf, including by adding this : 
```
 dns_canonicalize_hostname = false
```
But that's not the default so on all nodes using default krb5.conf (like on all laptops from contributors , etc) the default behaviour is to check DNS and follow to build the service principal through libkrb5

See https://web.mit.edu/kerberos/krb5-devel/doc/admin/princ_dns.html (thanks to Alexander for the link)

Let's confirm on a test  node that isn't enrolled but on which I can have a ticket: (simple curl request but same issue with python-requests-gssapi) : 

```
curl --negotiate -u : https://fasjson.stg.fedoraproject.org/v1/users/arrfab/groups/ --verbose
* About to connect() to fasjson.stg.fedoraproject.org port 443 (#0)
*   Trying 38.145.60.32...
* Connected to fasjson.stg.fedoraproject.org (38.145.60.32) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.stg.fedoraproject.org,O="Red Hat, Inc.",L=Raleigh,ST=North Carolina,C=US
* 	start date: Mar 25 00:00:00 2020 GMT
* 	expire date: Mar 30 12:00:00 2022 GMT
* 	common name: *.stg.fedoraproject.org
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /v1/users/arrfab/groups/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: fasjson.stg.fedoraproject.org
<snip>
* gss_init_sec_context() failed: : Server HTTP/wildcard.stg.fedoraproject.org@STG.FEDORAPROJECT.ORG not found in Kerberos database
<snip>
{"message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."}
* Connection #0 to host fasjson.stg.fedoraproject.org left intact

```

Clearly issue and mismatch between fasjson.stg.fedoraproject.org and wildcard.stg.fedoraproject.org (see issue above)
So let's use a workaround locally through /etc/hosts : (with 38.145.60.32 fasjson.stg.fedoraproject.org) and let's try same curl request : 

```
* About to connect() to fasjson.stg.fedoraproject.org port 443 (#0)
*   Trying 38.145.60.32...
* Connected to fasjson.stg.fedoraproject.org (38.145.60.32) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.stg.fedoraproject.org,O="Red Hat, Inc.",L=Raleigh,ST=North Carolina,C=US
* 	start date: Mar 25 00:00:00 2020 GMT
* 	expire date: Mar 30 12:00:00 2022 GMT
* 	common name: *.stg.fedoraproject.org
* 	issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /v1/users/arrfab/groups/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: fasjson.stg.fedoraproject.org
> Accept: */*
> 
<snip>
* Ignoring the response-body
* Connection #0 to host fasjson.stg.fedoraproject.org left intact
* Issue another request to this URL: 'https://fasjson.stg.fedoraproject.org/v1/users/arrfab/groups/'
* Found bundle for host fasjson.stg.fedoraproject.org: 0x24c7fe0
* Re-using existing connection! (#0) with host fasjson.stg.fedoraproject.org
* Connected to fasjson.stg.fedoraproject.org (38.145.60.32) port 443 (#0)
* Server auth using GSS-Negotiate with user ''
<snip>
{"result": [{"groupname": "sig-cloud", "uri": "http://fasjson.stg.fedoraproject.org/v1/groups/sig-cloud/"}]}
* Closing connection 0
```

So same requests worked fine now ..
Can a Fedora Sysadmin push the needed changes in stg.fedoraproject.org dns zone ? That would unblock this but also without that it wouldn't be really possible to query fasjson from contributor laptops (or other nodes not enrolled)

**Comment by abompard** [comment]
We are going to have to deploy some krb5 config on user's laptop to setup realm anyway, no? Then we could set `dns_canonicalize_hostname` to `false` at that point, couldn't we?

**Comment by arrfab** [comment]
let me disagree as it's from [libdefaults] so unsure about how/why we should modify default settings on people's machines (and possibly modifying their setup for their other krb5 setup). If only that was possible through a file for specific REALM or domain that would be possible but it's not.
So just one (or two) records in a DNS zone would easy to solve (and probably following the official and recommended way to set it up)

And even if we had to set something locally for STG, we can still rely on DNS and SRV lookup to find the correct kdc for fedoraproject.org (so no need to distribute a krb5.conf.d/file)

**Comment by abompard** [comment]
Sure, I'm not the one maintaining the zones, so I don't know which is easiest :-)

**Comment by smooge** [comment]
Have made the change. Should start to percolate out in 1 hour.

**Comment by smooge** [comment]
[smooge@linode01 ~]$ host fasjson.stg.fedoraproject.org
fasjson.stg.fedoraproject.org has address 38.145.60.33
fasjson.stg.fedoraproject.org has address 38.145.60.32
[

**Comment by arrfab** [comment]
Thanks a lot. Worth documenting that requirement for the prod and so not forget ? or just keep this one open as reminder ?
