### ISSUE TITLE
bump and build centos-packager for centos SIG members

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#23]
While waiting for fasjson-client packaged as RPM, we'll need to also modify centos-packager to have Requires: on fasjson-client in the future and centos-cert script being a simple wrapper for `fasjson-client get-cert -u <username>` and sanity checks like openssl validity

**Comment by arrfab** [comment]
Already worked on wrapper script but actually still blocked by lack of python-fasjson-client rpm package (see  https://github.com/fedora-infra/fasjson-client/issues/47)

**Comment by StephenCoady** [comment]
@arrfab Do you know if this ticket can be moved to done now, or if there is still work outstanding?

**Comment by arrfab** [comment]
It's done , through a copr repo, but is the fasjson-client pkg not itself available in epel8 ?

**Comment by StephenCoady** [comment]
@arrfab looks like it is: https://koji.fedoraproject.org/koji/search?terms=python-fasjson-client-0.1.1-6.el8&type=build&match=glob

**Comment by arrfab** [comment]
@StephenCoady yes, I just verified and it entered epel8 so let's close this ticket :)
