### ISSUE TITLE
Get mailman working in staging for testing/integration needs.

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/aaa-tracker#24]
Update:

Currently waiting on mailman to be packaged by a 3rd party before this can be progressed.

Will revert to this ticket once we can work on it.

**Comment by StephenCoady** [comment]
@abompard could you give some details on this one? Not sure my description above is accurate as I see that mailman is packaged already.

**Comment by markobrien1** [comment]
I'll look into this

**Comment by markobrien1** [comment]
Mailman uses ipsilon for auth so may not need any change for noggin

**Comment by StephenCoady** [comment]
Deploy mailman admin UI in staging and try to log in, if this works then we should be OK. No mailing lists needed.

Ideally this work should be done before we go to production in case there are issues.
