### ISSUE TITLE
Basset needs a Noggin plugin

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/aaa-tracker#25]
https://pagure.io/basset/pull-request/19

**Comment by StephenCoady** [comment]
@abompard I converted this from a note because I couldn't comment.

Will a review from someone within the team suffice or does it need to ideally be the repo maintainer?

**Comment by abompard** [comment]
I think someone within the team will be good enough, I'm already a co-maintainer of Basset so I'll be able to merge it once it passes review.

**Comment by StephenCoady** [comment]
@abompard sorry for the delay. I've reviewed and think its good to go.
