### ISSUE TITLE
Sort out host based access control

### ISSUE THREAD

**Issue by abompard** [fedora-infra/aaa-tracker#26]
Currently access control is done via fas-client.
In `inventory/group_vars/mbs_backend` there would be  "`fas_client_groups: sysadmin-noc,sysadmin-releng,sysadmin-mbs,sysadmin-veteran`"

We need an ansible task that will translate that into ipa operations. MBS is a good start.

**Comment by nirik** [comment]
Ideally this would be: 

* users in groups listed in ansible for a host would be allowed ssh access to the host. 
* some way to manage sudo rules per host/group. (Right now those are in ansible-private). Ideally forcing 2fa for those allowed to sudo at all.

**Comment by nphilipp** [comment]
> Ideally this would be:
> 
> * users in groups listed in ansible for a host would be allowed ssh access to the host.

Isn't this what's done with setting `fas_client_groups` plus classic FAS2 right now?

> * some way to manage sudo rules per host/group. (Right now those are in ansible-private). Ideally forcing 2fa for those allowed to sudo at all.

Not sure, isn't this beyond the scope of the ticket?

**Comment by nphilipp** [comment]
Note to self: "use what IPA provides" (per chat on IRC)

**Comment by nphilipp** [comment]
This implements HBAC access to groups configured in Ansible for IPA clients:

https://pagure.io/fedora-infra/ansible/pull-request/344

Here's the PR adding an `ipaclient` host in tiny-stage which I used for testing:

https://github.com/fedora-infra/tiny-stage/pull/22

**Comment by abompard** [comment]
At the moment ssh access still allows password logins. We need to disallow that. We already set `PasswordAuthentication no` in `sshd_config` so we need to understand why it's not sufficient to disable password auth.

See [Kevin's comment](https://pagure.io/fedora-infrastructure/issue/9152#comment-711593).

**Comment by nphilipp** [comment]
The SSH issue seems to have been solved meanwhile.

In other news, the ipa/client role in Ansible is more efficient now: https://pagure.io/fedora-infra/ansible/pull-request/402

**Comment by nphilipp** [comment]
Here's a PR setting the IPA variables for fedorapeople: https://pagure.io/fedora-infra/ansible/pull-request/459

Running the ipa/client portion of the playbook with this needs the `fedora-contributors` group talked about in https://pagure.io/fedora-infra/ansible/pull-request/435

**Comment by nphilipp** [comment]
Meanwhile, having bastion inherit batcave's shell groups works, too: https://pagure.io/fedora-infra/ansible/pull-request/504

Closing.
