### ISSUE TITLE
Wiki/Documentation about upcoming changes for CentOS SIG users (new fajson, new URLs, procedures, etc)

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#27]
Now that we have ansible roles converted to new Auth systems, and that we started to deploy/reconvert applications in STG environment, we should start writing public content that we can refer people to (like wiki.centos.org) and  use that in all future communications plan around the prod migration

**Comment by ryanlerch** [comment]
We kind of need to figure out a list here of what needs to be done here to consider this one Done. 

Is it a document describing the differences between the old way and the new way, 

and / or

updating current documentation on the wiki to the new way.

**Comment by arrfab** [comment]
both in fact, in my personal test copr repo with new tool, I have very basic doc for the fasjson-client : https://copr.fedorainfracloud.org/coprs/arrfab/fasjson-client/
But it would need to be pushed to wiki and other potential pages, and mail sent to centos-devel etc
Of course that means we have to have fasjson-client and others going live in real repositories (and not copr) first
