### ISSUE TITLE
Convert Openshift/OCP to new auth (staging) to test that it still works "transparently" when switching upstream IdP for OpenIDC

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#29]
Openshift/OCP uses OpenIDC against know IdP (ipsilon in our cases). We already tested that it works fine with OpenID for other applications, but we should now test OCP.stg.ci cluster auth switch

**Comment by arrfab** [comment]
I'll ping @davidkirwan (and Mark/Vipul) for auth switch for ocp.stg.ci cluster and see if that still continue to work. We'll put that in Review and ask for comments when we'll work on it

**Comment by arrfab** [comment]
We've worked together with @davidkirwan and migrated (easily) https://console-openshift-console.apps.ocp.stg.ci.centos.org/dashboards cluster STG OCP to new auth. Only note when adding (instead of just replacing) way to authenticate is to ensure that `mappingMethod:` isn't `claim` but `add`

**Comment by davidkirwan** [comment]
+1 wfm

**Comment by markobrien1** [comment]
+1 wfm. Thanks arrfab

**Comment by Zlopez** [comment]
+1 wfm. I just noticed the e-mail for password reset was sent from `fas@fedoraproject.org` and the e-mail I have in my ACO is different then the one you sent the e-mail to.

**Comment by arrfab** [comment]
@Zlopez yes, https://accounts.stg.centos.org and https://admin.stg.fedoraproject.org/accounts *are* just two noggin instances deployed on the same openshift, and so talking to same IPA backend (converged/merged one). So they are configured to send from that email address you mentioned.

Now, as I mentioned to @davidkirwan , if people suddenly change/update their email address in noggin (or in ACO/FAS), and that in openshift the `preferredUsername` parameter is set to `email` that can be problematic (instead of `name` or `nickname`) as on next login in openshift, it would probably consider it a *new* user. Worth investigating but that's something that was probably already there before (that parameter in .yaml file for oAuth).

What would be good to test (but wasn't in this scope but good to have a  look at) is how OpenShift would automatically inherits group memberships attributes through OpenIDC and so no need to create groups and assigned users *inside* Openshift to map to projects, etc ..

**Comment by ryanlerch** [comment]
Is this ticket closed now? or is there still more to be done here?

**Comment by arrfab** [comment]
with enough positive feedback we can consider that it's working fine, so let's close it
*normally* I initially thought that it had to be discussed during review and then moved .. but maybe each team is applying different principles : 
@amoloney1 ^
