### ISSUE TITLE
Enrolled CentOS VM (for admin tasks - prod)

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#3]
CentOS needs a VM that has network access to IPA (prod instance) to production integration, and that is enrolled in IPA

**Comment by arrfab** [comment]
Deployed the VMs needed for centos roles and trying to enroll these into IPA, but it seems that some internal SRV records are missing from internal fedoraproject.org zone : 

```
2021-01-21T15:09:43Z DEBUG Starting IPA discovery with domain=fedoraproject.org, servers=None, hostname=<removed>
2021-01-21T15:09:43Z DEBUG Search for LDAP SRV record in fedoraproject.org
2021-01-21T15:09:43Z DEBUG Search DNS for SRV record of _ldap._tcp.fedoraproject.org
2021-01-21T15:09:43Z DEBUG DNS record not found: NXDOMAIN
2021-01-21T15:09:43Z DEBUG No LDAP server found
2021-01-21T15:09:43Z DEBUG IPA Server not found

```

I was hoping that we could rely on DNS for redundancy and not specifying --server for ipa-client-install role.
I see that it's the default for fedora infra : https://pagure.io/fedora-infra/ansible/blob/main/f/roles/ipa/client/tasks/main.yml#_16
While for centos I decided to support both (https://github.com/CentOS/ansible-role-ipa-client/blob/master/tasks/main.yml#L23), I still think that for real redundancy ipa clients should rely on dns to automatically find available IPA servers, and so not always pointing to a static one.

@nirik , @smooge @abompard : opinions ? ^ 

Just adding some links to doc : 
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/planning_identity_management/index#planning-your-dns-services-and-host-names-planning-dns-and-host-names
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/installing_identity_management/index#dns-requirements-for-ipa-clients_preparing-the-system-for-ipa-client-installation
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/installing_identity_management/index#installing-an-ipa-server-without-integrated-dns_installing-identity-management

**Comment by nirik** [comment]
ok, here's proposed changes for both prod and stg, does this look correct?

The _ldap ones are in a 'iad2' view that should only be visible to machines in those ip blocks.

```
diff --git a/fedoraproject.org.template b/fedoraproject.org.template
index 98abab7d..8fd0545f 100644
--- a/fedoraproject.org.template
+++ b/fedoraproject.org.template
@@ -408,12 +408,19 @@ ipa             IN      A       10.3.163.54
 ipa             IN      A       10.3.163.55
 ipa01           IN      A       10.3.163.54
 ipa02           IN      A       10.3.163.55
+_ldap._tcp      IN SRV 0 100 389 ipa01.iad2.fedoraproject.org.
+_ldap._tcp      IN SRV 0 100 389 ipa02.iad2.fedoraproject.org.
+; staging
+_ldap._tcp.stg  IN SRV 0 100 389 ipa01.stg.iad2.fedoraproject.org.
 {% endif %}
 *.id            IN    CNAME wildcard
 kerneltest      IN    CNAME wildcard
 sso             IN    CNAME wildcard
+; external ipa records for prod and staging
 _kerberos._tcp  IN    SRV   20 1 1088 id.fedoraproject.org.
 _kerberos       IN    TXT   "FEDORAPROJECT.ORG"
+_kerberos._tcp.stg  IN    SRV   20 1 1088 id.stg.fedoraproject.org.
+_kerberos.stg   IN TXT "STG.FEDORAPROJECT.ORG"
 ; draft-mccallum-kitten-krb-service-discovery-03
 _kerberos       IN    URI   10  1 "krb5srv:m:kkdcp:https://id.fedoraproject.org/KdcProxy/"
 
diff --git a/master/vpn.fedoraproject.org b/master/vpn.fedoraproject.org
index 45b037f7..24070d2f 100644
--- a/master/vpn.fedoraproject.org
+++ b/master/vpn.fedoraproject.org
@@ -242,3 +242,7 @@ vpn.fedoraproject.org. IN DNSKEY 257 3 14 OD2abfcLRo/vJtVKF91Ar6xZ+IPDGi9hV0MP1W
 ; Publish: 20201104203017 (Wed Nov  4 20:30:17 2020)
 ; Activate: 20201104203017 (Wed Nov  4 20:30:17 2020)
 vpn.fedoraproject.org. IN DNSKEY 256 3 14 2IYfM38Ozc4VpztSrHBxh7fAkrQuQeMQnhLdBbAYi7uMF3GLNvMAsirG OjGU88ODx7LbuVcAkPUeijGIhkfz1Wh2WGx6iSMA/rjf+imvVKaf0P4C cshdhDC9Ul8IvDX5
+
+; ipa for vpn hosts
+_ldap._tcp      IN SRV 0 100 389 ipa01.vpn.fedoraproject.org.
+_ldap._tcp      IN SRV 0 100 389 ipa02.vpn.fedoraproject.org.
```

**Comment by arrfab** [comment]
Yeah, LGTM !

BTW, for the SRV record for _ldap._tcp, you can also (if you like) set different priorities (they are actually both set to same one, aka `0`) and also tune next value for weight (actually both set to `100`) but that's good, it should  then load-balance to both ipa servers equally

**Comment by nirik** [comment]
Pushed. Let me know if you hit any issues with it.

**Comment by arrfab** [comment]
cool , I confirm that it resolves through dig request

```
dig -t SRV _ldap._tcp.fedoraproject.org +short
0 100 389 ipa01.iad2.fedoraproject.org.
0 100 389 ipa02.iad2.fedoraproject.org.
```
I'll test to enroll node but probably tomorrow as working now on something else for Stream ;-)

Thanks a lot!

**Comment by arrfab** [comment]
@nirik : I confirm that using dns deploy option (https://github.com/CentOS/ansible-role-ipa-client/blob/master/defaults/main.yml#L15) it worked like a charm.
Closing this one as it's now deployed and working
