### ISSUE TITLE
Configure sudo access on IPA client hosts

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/aaa-tracker#31]
* Configure IPA so that only certain groups can use sudo (to become root) on a host.
* Bonus points: Configure IPA or sudo locally on hosts so that 2FA is mandatory for using sudo.

**Comment by nphilipp** [comment]
@nirik I assume we'll want a separate variable to configure sudo access, e.g. `ipa_client_sudo_groups`. Does that sound right?

**Comment by abompard** [comment]
According to [Kevin's comment](https://pagure.io/fedora-infrastructure/issue/9152#comment-711593), making 2FA auth mandatory for using sudo is not a bonus point.
Let's consider it part of the acceptance criteria for this ticket. Or I can open a new ticket for that if you prefer.

**Comment by abompard** [comment]
Also, in the same comment : 
> The sudo rules don't seem 100% yet... for example, breilly is in sysadmin-mbs, which is in ipa_client_sudo_groups on mbs-backend01.stg, but when they sudo they get:
> " user NOT authorized on host"

**Comment by nphilipp** [comment]
> Let's consider it part of the acceptance criteria for this ticket. Or I can open a new ticket for that if you prefer.

I've created #35 for sudo & 2FA.

**Comment by nphilipp** [comment]
> Also, in the same comment :
> 
> > The sudo rules don't seem 100% yet... for example, breilly is in sysadmin-mbs, which is in ipa_client_sudo_groups on mbs-backend01.stg, but when they sudo they get:
> > " user NOT authorized on host"

This is fixed: @markobrien1 and I looked into the IPA rules and on the box in question which checked out fine, then asked breilly who confirmed that the problem went away between last Friday and Monday.

**Comment by nphilipp** [comment]
Here's the Ansible PR covering shell-access and sudo rules: https://pagure.io/fedora-infra/ansible/pull-request/374

**Comment by nphilipp** [comment]
And it's merged.
