### ISSUE TITLE
Add userCerts profile and ACL in IPA prod

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#33]
For FASJSON to be able to issue correct TLS certificates, the  `userCerts` profile and CA ACL must be implemented in prod IPA.
That would reflect what has been done in the STG IPA environment

**Comment by arrfab** [comment]
blocks #32

**Comment by abompard** [comment]
It's in Ansible already so it should get deployed to prod when we move.

**Comment by arrfab** [comment]
Let me reopen as for CentOS preparation I need that *before* the real migration happen : I have to stage all our service accounts/keytab/TLS certificates, so in theory, I don't see any reason why they can't be created already in advance (especially if nothing uses them so no "break")

**Comment by StephenCoady** [comment]
@arrfab could you check if this work is ok and has been reviewed? looking to close tickets.

**Comment by arrfab** [comment]
It was done for prod, so let me close this .. Let's see about the .stg. status though but for a different thread
