### ISSUE TITLE
Make 2FA work with sudo and IPA

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/aaa-tracker#35]
Follow up to #31. We need to enforce two factor authentication with sudo access, this is not optional.

Background: [Kevin's](https://pagure.io/fedora-infrastructure/issue/9152#comment-711593) and [Aurelien's](https://pagure.io/fedora-infrastructure/issue/9152#comment-712084) comments and those in between.

I understand these and other comments around the topic like this: using sudo—to become root, or for everything?—must require 2FA i.e. the normal user password or a separate one plus crypto token. Is that about right, @nirik?

**Comment by nphilipp** [comment]
@abompard @nirik I've looked a bit into how we're doing sudo & 2FA today and I wonder…  can't we keep using `pam_url.so` in conjunction with `totpcgi` but configure the latter to verify the user’s password by doing an LDAP bind in their name, as described [here](https://serverfault.com/questions/447265/google-authenticator-with-openldap-or-fedora-389-server-or-freeipa#comment501939_457448)? We probably would have to separate `totpcgi` from FAS deployment-wise.

**Comment by nirik** [comment]
Yeah, we could keep using pam_url totpcgi, but I'd rather not if we can avoid it. :) 
totpcgi is a bunch of php. It runs in the same project as fas in openshift (but seperate pods and db).

I think we can consider that a fallback, but I would really prefer to move to noggin/ipa otp. ;)

**Comment by markobrien1** [comment]
This PR has now been updated which should inlcude all the hosts in staging https://pagure.io/fedora-infra/ansible/pull-request/396#. 

@nphilipp  has made updates which allow sudo with 2fa to work which we have tested in a number of staging hosts such as osbs and mbs so I would be happy to roll it out to all of staging if the PR is accepted

**Comment by markobrien1** [comment]
Currently it is up to the user to set an otp token for themselves and if they don't then they can sudo with password auth only.

There is no functionality at the moment to only allow sudo for users with otp enabled but this PR has been raised upstream to solve that https://github.com/SSSD/sssd/pull/5494/files

There is no indication on a timeline for availability of this as of yet though.

The only other option I could think of is to manually enforce it. Have some scripting to tell us what users in the sysadmin-* groups don't have otp enabled and politely ask them to do so.

**Comment by nirik** [comment]
> The only other option I could think of is to manually enforce it. Have some scripting to tell us what users in the sysadmin-* groups don't have otp enabled and politely ask them to do so.

I suppose we could do that for now... give some kind of grace period when we switch and then check everyone in sysadmin* and remove them if they don't add a token.
