### ISSUE TITLE
Deploy a CentOS version of noggin in prod

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#37]
Same thing that was already done for stg : deploy a  noggin portal that can be reached by haproxy for centos prod infra

**Comment by arrfab** [comment]
Basically replaying for prod the task #19 that was already done for staging

**Comment by abompard** [comment]
Done!

**Comment by arrfab** [comment]
@abompard  : Just tested but answer I get from your openshift deploy is "Application is not available" so are you sure that it knows the ingress route/name is accounts.centos.org (check how we did it for accounts.stg.centos.org) as it seems it doesn't find it through forwarded SNI setting from haproxy

**Comment by arrfab** [comment]
seems that it has been fixed and now working, closing
