### ISSUE TITLE
Create Roadmap for production deployment

### ISSUE THREAD

**Issue by markobrien1** [fedora-infra/aaa-tracker#39]
We need to create a list to decide what order AAA should be deployed to the servers in production. In case there are any unforseen issues it would be wise to leave the more important services to last when rolling out.

**Comment by StephenCoady** [comment]
Copying @nirik's email here for safe keeping and discussion.

> There was some discussion on deployment plans in:
> https://pagure.io/fedora-infrastructure/issue/9152#comment-711593
> 
> basically my thought was:
> 
> * deploy noggin in prod (we could really do this anytime I think?)
> * if we can do the sync without outage, do it.
> * keep syncing from fas changes.
> * schedule/announce outage and changes <- lots of loud announcing
>         * the ssh://username to ssh://git change on src
>         * the otp related issues (should enroll if sysadmin, extra steps
>         for kinit, etc)
>         * group changes (no admins, no self join)
>         * note what accounts were not synced.
> 
> on outage day/time:
> * take down fas (or make it ro or whatever)
> * final sync of any last minute data (or full sync if we can't do this
> without outage)
> * Make sure:
> ** users can push to src via ssh and https
> ** users can get a kerberos ticket
> ** users can login to apps via ipsilon/kerberos (especially koji/bodhi)
> ** centos users can do what they need to do
> 
> only once all thats working and seems good:
> (I'd be fine if this was the next day or whatever, we can wait)
> * remove fasClient from * (including package and nsswitch.conf changes
> and pam_url and... all /home/fedora* from most machines (except
> batcave probibly).
> * enroll all hosts as ipa clients
> * confim ssh / sudo all work as expected on all hosts.
> * profit!
> 
> So, I think we can do it in a day or two... the hosts/ssh/sudo stuff is
> just us admins, we are much more forgiving and can communicate changes
> than everyone else. It's the users switchover we need to be smooth. :)
> 
> So, if we avoid freeze, what would you all think of scheduling the
> outages for the 17th/18th? Is that too late?

**Comment by amoloney1** [comment]
Here is a first pass of a checklist we need to use for Noggin deployment to production
https://hackmd.io/@Ap8CkTlpSfmjb44UGV-kWA/HydTb48X_/edit

@nphilipp @StephenCoady @ryanlerch @markobrien1 @abompard @pypingou @nirik 

Can you please take a look and edit where needed? Especially on the machines and services listings :)

Thanks!

**Comment by nirik** [comment]
Looks mostly good to me. I think we may have to remove fas-clients/pam_url and /home/fedora/* before enabling sssd on the hosts however (otherwise it's going to get really confusing). 
Also, we probably should do batcave01 differently (save off the homedirs and chown them to the new uids?) or at least yell at people to save off anything they don't want to loose.
