### ISSUE TITLE
deploy a small kojihub/web/builder setup to test new x509 certs from IPA

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/aaa-tracker#5]
As we'll have to switch host/users TLS certs authentication, one test will be to deploy (ephemeral VMs) through existing ansible role[s$ a small setup and using new certs generated (see existing SOP for CentOS) from dogtag/IPA and confirm that we have a fully functional test (login to kojihub, request build, build, tag, etc)

If that works, we can have a plan to use Staging to test a convert of existing deployed kojihub instance and reflect a cert replacement, and that users would still be able to connect and be identified (we need another script/spike to reflect group membership, as it would be different from FAS api to fasjson)

**Comment by arrfab** [comment]
Kojihub deployed by ansible with new/fresh TLS certs coming from IPA and basic user cert for admin right seems to work : 
```
hallo, cbs-koji!

You are using the hub at https://koji.dev.centos.org/kojihub
Authenticated via client certificate /etc/pki/koji/cbs-ipa-dev-koji.pem
```
Next step is adding one kojid builder and see if tasks are picked up but afaics, basic x509 is working so should work without any issue

**Comment by arrfab** [comment]
ansible-role-kojid was played in that env, and it's also authenticating fine with the hub, also using certs from IPA : 
```
[cbs-koji@koji-0 ~]$ koji list-hosts
Hostname              Enb Rdy Load/Cap  Arches           Last Update
koji-1.dev.centos.org Y   Y    0.0/20.0 i386,x86_64      2020-10-19 11:59:05
```

**Comment by arrfab** [comment]
Starting migrating existing other koji instance for STG tests, and I'll ask for feedback from existing SIG members to confirm that it works after migration

**Comment by arrfab** [comment]
Worked with someone external/contributor (@alphacc) to test converting existing kojihub/kojiweb/kojid instance and it worked.
We just found a very small issue that was quickly fixed and pushed to staging branch of the kojihub role (https://github.com/CentOS/ansible-role-kojihub/commit/7fe879198654ae8eeae59b1073dd6d55a8813cbd)

Waiting for some more tests, including signing workflow end-to-end and if that works, we'll probably have reviewed it

**Comment by alphacc** [comment]
It looks good from my side, few improvements can be done with the sync scripts to improve logging/error management, but all necessary workflows have been tested with the new AAA. Thanks @arrfab !

**Comment by arrfab** [comment]
Just for the sake of documenting what we tested : 
 * Switching kojihub TLS auth cert (and using new CA)
 * testing that service account (koji and kojira) would still access reconfigured kojihub
 * reconfiguring (ansible) kojid instance with new TLS certs
 * testing that users/groups permissions was correctly being synced from upstream fasjson.stg.fedoraproject.org (IPA)
   * adding a user in a group => got automatically build permission for the tag/SIG group relationship
 * testing that kojihub could also publish (json payload) to mqtt broker, also reconfigured with new TLS certs
   * testing downstream action with rpm signing for tags (subscribed to mqtt) and pushing back signed rpm to koji

Apart from small (and easy fix) mentioned above, all was fine, so we should be "good to go" for prod deployment when we want to announce Auth switch

**Comment by ryanlerch** [comment]
Is this ticket closed now? or is there still more to be done here?

**Comment by arrfab** [comment]
We can close it with only one external feedback but I guess we'll not have more and it's enough for now
